document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"zh\">");
document.writeln("<head>");
document.writeln("    <title>极客导航</title>");
document.writeln("    <meta charset=\"UTF-8\">");
document.writeln("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">");
document.writeln("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
document.writeln("    <meta name=\"referrer\" content=\"origin\">");
document.writeln("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">");
document.writeln("    <meta name=\"author\" content=\"geeknav\">");
document.writeln("    <meta name=\"keywords\" content=\"GeekNav,极客喵,geeknav,极客导航,极客俱乐部,程序员导航,在线工具导航,设计素材,人工智能,noip,csp,noi,acm\">");
document.writeln("    <meta name=\"description\" content=\"极客导航是一个公益性平台\">");
document.writeln("    <meta property=\"og:image\" content=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/img/logo@2x.png\">");
document.writeln("    <meta property=\"og:type\" content=\"website\">");
document.writeln("    <meta property=\"og:url\" content=\"https://open985.com\">");
document.writeln("    <meta property=\"og:title\" content=\"GeekNav\">");
document.writeln("    <meta property=\"og:description\" content=\"极客导航是一个公益性平台\">");
document.writeln("    <meta property=\"og:site_name\" content=\"GeekNav\">");
document.writeln("    <meta name=\"twitter:card\" content=\"summary_large_image\">");
document.writeln("    <meta name=\"twitter:title\" content=\"GeekNav\">");
document.writeln("    <meta name=\"twitter:description\" content=\"极客导航是一个公益性平台\">");
document.writeln("    <meta name=\"baidu-site-verification\" content=\"xihr4MAXCX\" />");
document.writeln("	<meta name=\"theme-color\" content=\"RGB(254,50,87)\">");
document.writeln("    <link rel=\"shortcut icon\" href=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/search.svg\">");
document.writeln("    <link href=\"https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">");
document.writeln("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/css3/search2.css\">");
document.writeln("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/css3/demo2.css\" />");
document.writeln("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/css3/component2.css\" />");
document.writeln("	<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/css3/organicfoodicons2.css\" />");
document.writeln("    <link href=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/css3/styles.css\" rel=\"stylesheet\">");
document.writeln(" <!--    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/css/search.css\">-->");
document.writeln("	<!-- demo styles -->");
document.writeln("	<!--<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/css/demo.css\" />-->");
document.writeln("	<!-- menu styles -->");
document.writeln("	<!--<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/css/component.css\" />-->");
document.writeln("	<!-- icons -->");
document.writeln("	<!--<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/css/organicfoodicons.css\" />-->");
document.writeln("</head>");
document.writeln("  <body ondblclick=\"bg()\">");
document.writeln("        <button class=\"action action--open\" aria-label=\"Open Menu\"><span class=\"icon icon--menu\"></span></button>");
document.writeln("    <nav id=\"ml-menu\" class=\"geeknavmenu\">");
document.writeln("	<button class=\"action action--close\" aria-label=\"Close Menu\"><span class=\"icon icon--cross\"></span></button>");
document.writeln("	<div class=\"menu__wrap\">");
document.writeln("	<ul data-menu=\"main\" class=\"menu__level\">");
document.writeln("				 	<li class=\"menu__item\">");
document.writeln("	  			<a class=\"menu__link\" data-submenu=\"submenu-39\">极客的背包</a>");
document.writeln("			</li>");
document.writeln("		  	 			 			 			 			 			 			 	<li class=\"menu__item\">");
document.writeln("	  			<a class=\"menu__link\" data-submenu=\"submenu-24\">学习资源</a>");
document.writeln("			</li>");
document.writeln("		  	 			 			 			 			 			 			 			 	<li class=\"menu__item\">");
document.writeln("	  			<a class=\"menu__link\" data-submenu=\"submenu-17\">工具与生活</a>");
document.writeln("			</li>");
document.writeln("		  	 			 			 			 			 			 			 			 			 	<li class=\"menu__item\">");
document.writeln("	  			<a class=\"menu__link\" data-submenu=\"submenu-7\">设计素材</a>");
document.writeln("			</li>");
document.writeln("		  	 			 			 			 			 			 			 			 			 	<li class=\"menu__item\">");
document.writeln("	  			<a class=\"menu__link\" data-submenu=\"submenu-38\">办公素材</a>");
document.writeln("			</li>");
document.writeln("		  	 			 			 			 	<li class=\"menu__item\">");
document.writeln("	  			<a class=\"menu__link\" data-submenu=\"submenu-3\">灵感采集</a>");
document.writeln("			</li>");
document.writeln("		  	 			 			 			 			 	<li class=\"menu__item\">");
document.writeln("	  		<a class=\"menu__link\" data-submenu=\"submenu-menu2\">更多内容</a>");
document.writeln("			</ul>");
document.writeln("	");
document.writeln("		<ul data-menu=\"submenu-menu2\" class=\"menu__level\">");
document.writeln("					  	<li class=\"menu__item\">	  ");
document.writeln("				<a class=\"menu__link\" data-submenu=\"submenu-31\">人工智能</a>");
document.writeln("				</li>");
document.writeln("		  					  					  					  					  					  					  	<li class=\"menu__item\">	  ");
document.writeln("				<a class=\"menu__link\" data-submenu=\"submenu-58\">有趣人类</a>");
document.writeln("				</li>");
document.writeln("		  					  					  					  					  					  	<li class=\"menu__item\">	  ");
document.writeln("				<a class=\"menu__link\" data-submenu=\"submenu-47\">算法能力++</a>");
document.writeln("				</li>");
document.writeln("		  					  					  		</ul>");
document.writeln("		");
document.writeln("		 	<ul data-menu=\"submenu-39\" class=\"menu__level\">");
document.writeln("							<li class=\"menu__item\"><a class=\"menu__link\">博客与社区</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">必备论坛</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">编程文档</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">控制台直达</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">托管与公有库</a></li>");
document.writeln("						</ul>");
document.writeln("	 		 		 		 		 		 		 	<ul data-menu=\"submenu-24\" class=\"menu__level\">");
document.writeln("							<li class=\"menu__item\"><a class=\"menu__link\">课程集合</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">设计规范</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">视频教程</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">交互设计</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">设计文章</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">设计电台</a></li>");
document.writeln("						</ul>");
document.writeln("	 		 		 		 		 		 		 		 	<ul data-menu=\"submenu-17\" class=\"menu__level\">");
document.writeln("							<li class=\"menu__item\"><a class=\"menu__link\">在线工具-处理</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">在线工具-技术</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">在线配色</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">娱乐の工具</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">网页版IM</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">邮箱与网盘</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">系统镜像</a></li>");
document.writeln("						</ul>");
document.writeln("	 		 		 		 		 		 		 		 		 	<ul data-menu=\"submenu-7\" class=\"menu__level\">");
document.writeln("							<li class=\"menu__item\"><a class=\"menu__link\">图标素材</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">LOGO设计</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">平面素材</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">UI资源</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">Sketch资源</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">字体资源</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">Mockup</a></li>");
document.writeln("						</ul>");
document.writeln("	 		 		 		 		 		 		 		 		 	<ul data-menu=\"submenu-38\" class=\"menu__level\">");
document.writeln("							<li class=\"menu__item\"><a class=\"menu__link\">PPT资源</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">摄影图库</a></li>");
document.writeln("						</ul>");
document.writeln("	 		 		 		 	<ul data-menu=\"submenu-3\" class=\"menu__level\">");
document.writeln("							<li class=\"menu__item\"><a class=\"menu__link\">发现产品</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">界面灵感</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">网页灵感</a></li>");
document.writeln("						</ul>");
document.writeln("	 		 		 		 		 	<ul data-menu=\"submenu-31\" class=\"menu__level\">");
document.writeln("							<li class=\"menu__item\"><a class=\"menu__link\">开放能力平台</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">学习与交流</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">比赛平台</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">云端计算资源</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">官方文档</a></li>");
document.writeln("						</ul>");
document.writeln("	 		 		 		 		 		 		 	<ul data-menu=\"submenu-58\" class=\"menu__level\">");
document.writeln("							<li class=\"menu__item\"><a class=\"menu__link\">人工智能</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">算法导论</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">电子DIY</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">前端技术</a></li>");
document.writeln("						</ul>");
document.writeln("	 		 		 		 		 		 	<ul data-menu=\"submenu-47\" class=\"menu__level\">");
document.writeln("							<li class=\"menu__item\"><a class=\"menu__link\">在线做题</a></li>");
document.writeln("										<li class=\"menu__item\"><a class=\"menu__link\">参考文档</a></li>");
document.writeln("						</ul>");
document.writeln("		</div>");
document.writeln("	 		 		 		</nav>");
document.writeln("        <div id=\"content\" class=\"container\">");
document.writeln("		<header id=\"geekheader\" class=\"bp-header cf\">");
document.writeln("			<div class=\"dummy-logo\" id=\"geeklogo\">");
document.writeln("				<img id=\"geeknav\" onclick=\"window.open(\'https://tongji.baidu.com/web/welcome/ico?s=0815ca0ab4a5299677d0f428b281ffa1\', \'_blank\')\" src=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/img/logo.png\" width=\"288px\" height=\"87px\"/>");
document.writeln("			<!--onmouseover=\"tip(\'极客导航是一个公益性平台\',\'geeknav\',18000,2)\" onmouseout=\"tipx(i)\"-->");
document.writeln("			</div>");
document.writeln("			<div id=\"gk\" class=\"action action--open2\" aria-label=\"Open Menu\" onclick=\"opengeek()\"><span class=\"icon icon--menu\"></span></div>");
document.writeln("			<div class=\"bp-header__main\">");
document.writeln("				<span class=\"bp-header__present\">极客导航 <span id=\"about\" class=\"bp-icon bp-icon--about\" onmouseover=\"qrcode()\" onmouseout=\"tipx(i)\"></span></span>");
document.writeln("				<h1 class=\"bp-header__title\" id=\"got\" style=\"cursor:help\" onclick=\"window.open(\'https://translate.google.cn\')\">TranslateIt</h1>");
document.writeln("				<nav class=\"bp-nav\">");
document.writeln("					<a class=\"bp-nav__item bp-icon bp-icon--drop\" onclick=\"musicx(\'musicwindow\',\'\',\'https://music.ip3x.com/\',[\'70%\', \'85%\'])\" data-info=\"music\"><span>music</span></a>");
document.writeln("					<a class=\"bp-nav__item bp-icon bp-icon--archive\" onclick=\"codex(\'codewindow\',\'\',\'https://ide.open356.com/\',[\'70%\', \'85%\'])\" data-info=\"online ide\"><span>online ide</span></a>");
document.writeln("					<!--代码使用者不得删除本声明相关内容,请自重-->");
document.writeln("					<!--极客导航,官方开源地址:http://github.com/CrazyBoyM/geeknav-->");
document.writeln("					<!--代码使用者不得删除本声明相关内容,请自重-->");
document.writeln("				</nav>");
document.writeln("			</div>");
document.writeln("		</header>"); 
document.writeln("    <div class=\"main-content\">");
document.writeln("    	<h1 id=\"geektitle\" class=\"mediatitle\" onclick=\"back()\">极客导航</h1>");
document.writeln("    	<div id=\"geek\" class=\"content\">");
document.writeln("		<script type=\"text/javascript\" id=\"searchjs\" src=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/js/search.js\"></script>");
document.writeln("		<div class=\"geektext\">");
document.writeln("		<button id=\"geekbutton\" onclick=\"opengeek()\" class=\"geekbutton\">显示全部隐层</button>");
document.writeln("		<br>");
document.writeln("		<p id=\"geektext\" style=\"cursor:pointer;font-size:18px\" onclick=\"textforward()\">");
document.writeln("			Make your life legendary as well");
document.writeln("		</p>");
document.writeln("		</div>");
document.writeln("		</div>");
document.writeln("		<div id=\"geek2\" class=\"content2\" style=\"display:none;\">");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("	<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js\" integrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\" crossorigin=\"anonymous\"></script>");
document.writeln("	<script src=\"https://cdn.jsdelivr.net/npm/layui-layer@1.0.9/dist/layer.js\"></script>");
document.writeln("	<script src=\"https://cdn.jsdelivr.net/npm/blueimp-md5@2.12.0/js/md5.min.js\"></script>");
document.writeln("    <script src=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/data.js\"></script>");
document.writeln("	<script src=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/js/modernizr-custom.js\"></script>");
document.writeln("	<script src=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/js/classie.js\"></script>");
document.writeln("	<script src=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/js/main.js\"></script>");
document.writeln("    <script src=\"https://cdn.jsdelivr.net/gh/CrazyBoyM/cdn@latest/geeknav/js/geeks.js\"></script>");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");